int weee =(4+6-6/4509*20022%52);
println(weee);
boolean wewwew = (true && false)||false==false;
println(wewwew);
println(4*5);
boolean x = false==true;
boolean y = true&&false;
boolean e = true||false;
boolean  r = !true;
boolean d = true!=true;
println(d);
println(3<5&&9>10);
